clc
close all
clear all


load('nn_data.mat')

%Exclude group
Xsw(:,end)=[];

%% FIT NN
% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
nsubs=length(initial_pert);
inputs = [Xsw'; initial_pert']; %N_attributes X N_examples
targets = [1.4*ones(1,nsubs); 0.7*ones(1,nsubs)];

% Create a Fitting Network
hiddenLayerSize = 10;
net = fitnet(hiddenLayerSize);

% Set up Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 80/100;
net.divideParam.testRatio = 20/100;
%What happens when I do not specify a validation set?
% Train the Network
[net,tr] = train(net,inputs,targets);

% Test the Network
outputs = net(inputs);
errors = gsubtract(outputs,targets);
performance = perform(net,targets,outputs);

% Plot actual values VS predictions

% View the Network
view(net)

%Test new subject
randsub=rand(9,1);
newout=net(randsub);
