function [fitresult, gof] = createFit(stride_vec_iA1, iA1m)
%CREATEFIT(STRIDE_VEC_IA1,IA1M)
%  Create a fit.
%  
%  Data for 'iA1m' fit:
%      X Input : stride_vec_iA1
%      Y Output: iA1m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 15-Jun-2018 15:30:34
 

%% Fit: 'iA1m'.
[xData, yData] = prepareCurveData( stride_vec_iA1, iA1m );

% Set up fittype and options.
ft = fittype( '(a+b*exp(-x/c)+d*exp(-x/f))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.Lower = [-10000000000 -10000000000 0 -10000000000 0];
opts.StartPoint = [-0.5 -0.5 20 -0.5 20];
% opts.Upper = [10000000000 10000000000 10000000000 10000000000 10000000000];
opts.Lower = [-10e10  -10e10           1    -10e10         1  ];
opts.Upper = [+10e10  0       10e10    0       10e10];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'iA1m' );
h = plot( fitresult, xData, yData );
legend( h, 'iA1m vs. stride_vec_iA1', 'iA1m', 'Location', 'NorthEast' );
% Label axes
xlabel stride_vec_iA1
ylabel iA1m
grid on


